source $HOME/.vim/conf/init.vim         " basic inits, plugin manager
source $HOME/.vim/conf/main.vim         " main key mappings, history,...
source $HOME/.vim/conf/look.vim         " basic ui, colors, fonts,...
source $HOME/.vim/conf/edit.vim         " basic text editing settings
source $HOME/.vim/conf/nav.vim          " movement in file, windows, tabs, ...
source $HOME/.vim/conf/search.vim       " vim search, code search
source $HOME/.vim/conf/ide.vim          " IDE features: dir trees, syntax, ...
source $HOME/.vim/conf/shortabbr.vim    " shortcuts and abbreviations
